name: Publish

on:
  release:
    branches: [ master ]
    types: [ published ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install poetry
        run: |
             pip install poetry
             poetry config virtualenvs.create false

      - name: Publish
        run: poetry publish --build -n
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.POETRY_PYPI_TOKEN }}
